language: python
python:
  - "pypy"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
cache:
  - $HOME/.pip-cache
# command to install dependencies
install:
  - pip install -r requirements-travis.txt --download-cache $HOME/.pip-cache
  - pip install coveralls --download-cache $HOME/.pip-cache
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi  # needs for running tests
  - pip install --allow-all-external -e .
# command to run tests
script: make travis
after_success: coveralls
notifications:
  irc:
    channels:
      - "irc.thescoundrels.net#scoundrels"
    on_success: change
    on_failure: change
    use_notice: false
